### PR TITLE
Added Swedish translation

### PR DESCRIPTION
**Pull request by bsvensson**

### CODE REVIEW

**Comment by martynasma** [comment]
Cool, thanks!

Quick question: are months and weekdays all-lowercase intentionally?

**Comment by bsvensson** [comment]
> Quick question: are months and weekdays all-lowercase intentionally?

Yes, but really depends on context.  In general months and weekdays are all lowercase (as opposed to English), but if they're used as the first word in a sentence they would be uppercase.

**Comment by martynasma** [comment]
Thanks.

So in the situations where we display only month, like here `"_date_month": "MMM",` this would appear as lowercase.

This could happen, say we have a date-chart spanning a year. So we show a single grid line/label per month, which will display only month name. In this case, is it still OK to display it all lower-case?

**Comment by bsvensson** [comment]
For chart labels, like legends and sentences, I think sentence case, ie first letter uppercase would be better.  Maybe this is more common for amcharts.

But if your showing it combined with something like `2018 januari` or `31 januari`, then lowercase. 

@martynasma - Would you like me to update the pull request?

**Comment by martynasma** [comment]
Nah.

I'm glad we had this conversation. I can now see how neither solution is perfect.

So now I'm thinking maybe we should go with a lowercase (how you have it), but automatically uppercase the first letter of the formatted date.

This way months/weekdays will be correctly lowercase in the middle of the date, but will be uppercased when starting from month/weekday.

I'm gonna go and merge your PR now.

Thanks a lot!

**Pull request merged**
